# vim:fileencoding=utf-8:foldmethod=marker

include theme.conf

font_family MonoLisa
font_size 14.0
font_features MonoLisa +dlig +ss01 +ss02 +ss03 +ss06 +ss07 +ss08 +ss10 +ss16 +ss17
modify_font cell_height 140%
modify_font underline_position 4

hide_window_decorations titlebar-only
macos_quit_when_last_window_closed yes

map cmd+1 send_text all \x011
map cmd+2 send_text all \x012
map cmd+3 send_text all \x013
map cmd+4 send_text all \x014
map cmd+5 send_text all \x015
map cmd+6 send_text all \x016
map cmd+7 send_text all \x017
map cmd+8 send_text all \x018
map cmd+9 send_text all \x019
map cmd+n new_os_window_with_cwd
