#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m space 1 --label main
yabai -m space 2 --label docs
yabai -m space 3 --label code
yabai -m space 4 --label social

# send signals to sketchybar to update
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# global settings
yabai -m config external_bar all:$(($(sketchybar --query bar | jq .height) + 0)):0

options=(
  # external_bar main:28:0
  layout bsp
  window_gap 10
  top_padding 10
  bottom_padding 8
  left_padding 8
  right_padding 8
  mouse_modifier ctrl
  mouse_action1 move
  # mouse_action2 resize
  mouse_drop_action swap
  window_shadow off
  insert_feedback_color 0xff9dd274
  # New window spawns to the right if vertical split, or bottom if horizontal split
  window_placement second_child
  window_animation_duration 0.25
  window_opacity off
)

yabai -m config "${options[@]}"

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Todoist|1Password|Calculator|Software Update|Dictionary|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Xnapper|TablePlus|Activity Monitor|Font Book)$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Raycast Settings" manage=off

yabai -m rule --add app="^Brave Browser$" space=main
yabai -m rule --add app="^Obsidian$" space=docs
yabai -m rule --add app="^Ghostty$" space=code
yabai -m rule --add app="^Zed$" space=code
yabai -m rule --add app="^Telegram$" space=social
yabai -m rule --add app="^WhatsApp$" space=social
yabai -m rule --add app="^Zen$" space=social
yabai -m rule --add app="^Steam.?(Helper)?$" space=games manage=off
yabai -m rule --add label="Steam" space=games manage=off

echo "yabai configuration loaded.."
