#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m space 1 --label main
yabai -m space 2 --label docs
yabai -m space 3 --label code
yabai -m space 4 --label social

# send signals to sketchybar to update
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# global settings
options=(
  external_bar main:28:0
  layout bsp
  window_gap 10
  top_padding 10
  bottom_padding 8
  left_padding 8
  right_padding 8
  mouse_modifier ctrl
  mouse_action1 move
  # mouse_action2 resize
  mouse_drop_action swap
  window_shadow off
  insert_feedback_color 0xff9dd274
  # New window spawns to the right if vertical split, or bottom if horizontal split
  window_placement second_child
  window_animation_duration 0.25
  window_opacity off
)

yabai -m config "${options[@]}"

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Todoist|1Password|LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Enter the Gungeon|Xnapper|Rancher Desktop|TablePlus|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Raycast Settings" manage=off

yabai -m rule --add app="^Brave Browser$" space=web
yabai -m rule --add app="^Obsidian$" space=docs
yabai -m rule --add app="^Ghostty$" space=code
yabai -m rule --add app="^Zed$" space=code
yabai -m rule --add app="^Telegram$" space=social
yabai -m rule --add app="^WhatsApp$" space=social
yabai -m rule --add app="^Zen$" space=social

# run borders in the background
# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
