# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#81c8be" }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#e5c890", bold = true, italic = true, underline = true }
find_position = { fg = "#f4b8e4", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#a6d189", bg = "#a6d189" }
marker_cut = { fg = "#e78284", bg = "#e78284" }
marker_marked = { fg = "#81c8be", bg = "#81c8be" }
marker_selected = { fg = "#e5c890", bg = "#e5c890" }

# Tab
tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "#303446", bg = "#a6d189" }
count_cut = { fg = "#303446", bg = "#e78284" }
count_selected = { fg = "#303446", bg = "#e5c890" }

# Border
border_symbol = "│"
border_style = { fg = "#838ba7" }

# : }}}


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#51576d", bg = "#51576d" }

# Mode
mode_normal = { fg = "#303446", bg = "#8caaee", bold = true }
mode_select = { fg = "#303446", bg = "#a6d189", bold = true }
mode_unset = { fg = "#303446", bg = "#eebebe", bold = true }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8caaee", bg = "#51576d" }
progress_error = { fg = "#e78284", bg = "#51576d" }

# Permissions
permissions_t = { fg = "#8caaee" }
permissions_r = { fg = "#e5c890" }
permissions_w = { fg = "#e78284" }
permissions_x = { fg = "#a6d189" }
permissions_s = { fg = "#838ba7" }

# : }}}


# : Select {{{

[select]
border = { fg = "#8caaee" }
active = { fg = "#f4b8e4", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#8caaee" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#8caaee" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#8caaee" }
title = {}
hovered = { fg = "#f4b8e4", underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#414559" }
cand = { fg = "#81c8be" }
rest = { fg = "#949cbb" }
desc = { fg = "#f4b8e4" }
separator = "  "
separator_style = { fg = "#626880" }

# : }}}


# : Help {{{

[help]
on = { fg = "#81c8be" }
run = { fg = "#f4b8e4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#51576d", bg = "#c6d0f5" }

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "#a6d189" }
title_warn = { fg = "#e5c890" }
title_error = { fg = "#e78284" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#81c8be" },

	# Media
	{ mime = "{audio,video}/*", fg = "#e5c890" },

	# Archives
	{ mime = "application/*zip", fg = "#f4b8e4" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f4b8e4" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#a6d189" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#8caaee" },
]

# : }}}
