[mgr]
show_hidden = true
sort_dir_first = true

[preview]
max_width = 1024
max_height = 768
tab_size = 2
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[plugin]

prepend_previewers = [
  { url = "*.csv", run = "rich-preview"}, # for csv files
  { url = "*.md", run = "rich-preview" }, # for markdown (.md) files
  { url = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
  { url = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
  { url = "*.json", run = "rich-preview"}, # for json (.json) files
]
