[tools]
go = "latest"
node = 'lts'
ruby = "3.4.8"
yarn = "latest"
rust = "1.89.0"

"npm:typescript-language-server" = "latest"
"npm:context-mode" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@doist/todoist-cli" = "latest"
opencode = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "npm", "yarn", "bun"]
trusted_config_paths = ['~/Projects/']

[settings.npm]
package_manager = "pnpm"

[settings.ruby]
compile = false
