-- require("items.apple")
require("items.menus")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.volume")
require("items.battery")
require("items.prayers")
require("items.mr-rate")
require("items.wifi")
require("items.cpu")
