# Theme colors (auto-generated by theme-set — do not edit manually)
# Sourced by fish/config.fish

set -g fish_color_autosuggestion {{ color8_strip }}
set -g fish_color_cancel {{ color1_strip }}
set -g fish_color_command {{ color6_strip }}
set -g fish_color_comment {{ color8_strip }}
set -g fish_color_cwd {{ color3_strip }}
set -g fish_color_end {{ color3_strip }}
set -g fish_color_error {{ color1_strip }}
set -g fish_color_escape {{ color5_strip }}
set -g fish_color_gray {{ color8_strip }}
set -g fish_color_host {{ color4_strip }}
set -g fish_color_host_remote {{ color2_strip }}
set -g fish_color_keyword {{ color1_strip }}
set -g fish_color_normal {{ foreground_strip }}
set -g fish_color_operator {{ color5_strip }}
set -g fish_color_option {{ color2_strip }}
set -g fish_color_param {{ foreground_strip }}
set -g fish_color_quote {{ color2_strip }}
set -g fish_color_redirection {{ color5_strip }}
set -g fish_color_search_match --background={{ color0_strip }}
set -g fish_color_selection --background={{ color0_strip }}
set -g fish_color_status {{ color1_strip }}
set -g fish_color_user {{ color6_strip }}
