# Lazygit theme (auto-generated by theme-set — do not edit manually)
# This file is sourced via lazygit's config include mechanism or merged in.

gui:
  theme:
    activeBorderColor:
      - "{{ accent_strip }}"
      - bold
    inactiveBorderColor:
      - "{{ color0_strip }}"
    searchingActiveBorderColor:
      - "{{ color3_strip }}"
      - bold
    optionsTextColor:
      - "{{ color4_strip }}"
    selectedLineBgColor:
      - "{{ color0 }}"
    cherryPickedCommitFgColor:
      - "{{ color4_strip }}"
    cherryPickedCommitBgColor:
      - "{{ color5_strip }}"
    unstagedChangesColor:
      - "{{ color1_strip }}"
    defaultFgColor:
      - "{{ foreground_strip }}"
  authorColors:
    "*": "{{ accent }}"
