# Yazi theme (auto-generated by theme-set — do not edit manually)

[mgr]
cwd = { fg = "{{ color6 }}" }

find_keyword  = { fg = "{{ color3 }}", bold = true, italic = true, underline = true }
find_position = { fg = "{{ color5 }}", bg = "reset", bold = true, italic = true }

marker_copied   = { fg = "{{ color2 }}", bg = "{{ color2 }}" }
marker_cut      = { fg = "{{ color1 }}", bg = "{{ color1 }}" }
marker_marked   = { fg = "{{ color6 }}", bg = "{{ color6 }}" }
marker_selected = { fg = "{{ color3 }}", bg = "{{ color3 }}" }

tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

count_copied   = { fg = "{{ background }}", bg = "{{ color2 }}" }
count_cut      = { fg = "{{ background }}", bg = "{{ color1 }}" }
count_selected = { fg = "{{ background }}", bg = "{{ color3 }}" }

border_symbol = "│"
border_style  = { fg = "{{ color0 }}" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "{{ color0 }}", bg = "{{ color0 }}" }

mode_normal = { fg = "{{ background }}", bg = "{{ color4 }}", bold = true }
mode_select = { fg = "{{ background }}", bg = "{{ color2 }}", bold = true }
mode_unset  = { fg = "{{ background }}", bg = "{{ color5 }}", bold = true }

progress_label  = { bold = true }
progress_normal = { fg = "{{ color4 }}", bg = "{{ color0 }}" }
progress_error  = { fg = "{{ color1 }}", bg = "{{ color0 }}" }

perm_type  = { fg = "{{ color4 }}" }
perm_read  = { fg = "{{ color3 }}" }
perm_write = { fg = "{{ color1 }}" }
perm_exec  = { fg = "{{ color2 }}" }
perm_sep   = { fg = "{{ color8 }}" }

[select]
border   = { fg = "{{ color4 }}" }
active   = { fg = "{{ color5 }}", bold = true }
inactive = {}

[input]
border   = { fg = "{{ color4 }}" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "{{ color4 }}" }
active   = { reversed = true }
inactive = {}
icon_file    = ""
icon_folder  = ""
icon_command  = ""

[tasks]
border  = { fg = "{{ color4 }}" }
title   = {}
hovered = { fg = "{{ color5 }}" }

[which]
cols            = 3
mask            = { bg = "{{ color0 }}" }
cand            = { fg = "{{ color6 }}" }
rest            = { fg = "{{ color8 }}" }
desc            = { fg = "{{ color5 }}" }
separator       = "  "
separator_style = { fg = "{{ color0 }}" }

[help]
on      = { fg = "{{ color6 }}" }
run     = { fg = "{{ color5 }}" }
hovered = { reversed = true }
footer  = { fg = "{{ color0 }}", bg = "{{ foreground }}" }

[notify]
title_info  = { fg = "{{ color2 }}" }
title_warn  = { fg = "{{ color3 }}" }
title_error = { fg = "{{ color1 }}" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "{{ color6 }}" },

	# Media
	{ mime = "{audio,video}/*", fg = "{{ color3 }}" },

	# Archives
	{ mime = "application/{,g}zip", fg = "{{ color5 }}" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "{{ color5 }}" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "{{ color2 }}" },

	# Fallback
	{ name = "*", fg = "{{ foreground }}" },
	{ name = "*/", fg = "{{ color4 }}" },
]
